#Hugo configuration
title = "qwesdfd"
baseURL = "https:\/\/asdfdasf.sdf.er"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
galleryChannelIds = "85601876,85595611,83052333"

[params]
loginId = "1758823"
subfolder = ""
firstpartycookies = true
cookiedomain = "sdf.er"
